const DailyBibleVerses = [
    { text: "The Lord is my shepherd; I shall not want.", ref: "(Psalm 23:1)" },
    { text: "యెహోవా నా కాపరి; నాకు ఏమియు కొదువలేదు.", ref: "(కీర్తనల గ్రంథము 23:1)" },
    { text: "Commit your way to the Lord; trust in Him, and He will act.", ref: "(Psalm 37:5)" },
    { text: "నీ మార్గము యెహోవా వశము చేయుము; ఆయననుబట్టి భరోసా కలిగించుకొనుము, అప్పుడు ఆయన కార్యసిద్ధి చేసెను.", ref: "(కీర్తనల గ్రంథము 37:5)" },
    { text: "I can do all things through Christ who strengthens me.", ref: "(Philippians 4:13)" },
    { text: "నన్ను బలపరచు క్రీస్తు ద్వారా నేను అన్నియు చేయగలను.", ref: "(ఫిలిప్పీయులకు 4:13)" },
    { text: "Be strong and courageous. Do not be afraid; do not be discouraged.", ref: "(Joshua 1:9)" },
    { text: "ధైర్యముగా ఉండుము, నీరు భయపడవద్దు; దిగులుపడవద్దు.", ref: "(యెహోషువ 1:9)" },
    { text: "The steadfast love of the Lord never ceases; His mercies never come to an end.", ref: "(Lamentations 3:22)" },
    { text: "యెహోవా ప్రేమ శాశ్వతముగా నిలుచును; ఆయన కృపలు అంతము కలవు.", ref: "(విలాపవాక్యములు 3:22)" },
    { text: "Cast all your anxiety on Him because He cares for you.", ref: "(1 Peter 5:7)" },
    { text: "మీ ఆందోళన అంతా ఆయన మీద వేసి వేయుడి, ఆయన మిమ్మల్ని ప్రేమిస్తాడు.", ref: "(1 పేతురు 5:7)" },
    { text: "For God so loved the world that He gave His only Son.", ref: "(John 3:16)" },
    { text: "దేవుడు లోకాన్ని అంతగా ప్రేమించెను గనుక తన ఏకైక కుమారుని ఇచ్చెను.", ref: "(యోహాను 3:16)" },
    { text: "The Lord is near to all who call on Him.", ref: "(Psalm 145:18)" },
    { text: "యెహోవా తనను పిలిచినవారందరికి సమీపముగా ఉన్నాడు.", ref: "(కీర్తనల గ్రంథము 145:18)" },
    { text: "Do not be anxious about anything, but in everything by prayer and supplication with thanksgiving let your requests be made known to God.", ref: "(Philippians 4:6)" },
    { text: "ఏ విషయమునైనను ఆందోళన చెందవద్దు, కానీ ప్రార్థన ద్వారా దేవునికి తెలియజేయుడి.", ref: "(ఫిలిప్పీయులకు 4:6)" },
    { text: "Delight yourself in the Lord, and He will give you the desires of your heart.", ref: "(Psalm 37:4)" },
    { text: "యెహోవాలో ఆనందించుము, అప్పుడు ఆయన నీ హృదయాశయములను నీకిచ్చును.", ref: "(కీర్తనల గ్రంథము 37:4)" },
    { text: "My grace is sufficient for you, for my power is made perfect in weakness.", ref: "(2 Corinthians 12:9)" },
    { text: "నా కృప నీకు సరిపోతుంది, ఎందుకంటే బలహీనతలో నా శక్తి పరిపూర్ణమౌతుంది.", ref: "(2 కోరింథీయులకు 12:9)" },
    { text: "Blessed are the pure in heart, for they shall see God.", ref: "(Matthew 5:8)" },
    { text: "హృదయము పవిత్రముగలవారు ధన్యులు, వారు దేవునిని దర్శించుదురు.", ref: "(మత్తయి 5:8)" },
    { text: "The Lord is good, a stronghold in the day of trouble.", ref: "(Nahum 1:7)" },
    { text: "యెహోవా మంచివాడు, శ్రమలో ఆశ్రయ స్థలము.", ref: "(నాహూము 1:7)" },
    { text: "Draw near to God, and He will draw near to you.", ref: "(James 4:8)" },
    { text: "దేవునికి సమీపించుడి, ఆయన మీకు సమీపించును.", ref: "(యాకోబు 4:8)" },
    { text: "For I know the plans I have for you, declares the Lord, plans to prosper you and not to harm you.", ref: "(Jeremiah 29:11)" },
    { text: "నేను మీకొరకు ఉద్దేశించిన యోచనలు మీకు తెలుసు, అవి మేలు చేయు యోచనలు.", ref: "(యిర్మియా 29:11)" }
];

export default DailyBibleVerses;